-- CreateTable
CREATE TABLE "FormSubmission" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "businessEmailId" TEXT,
    "businessName" TEXT NOT NULL,
    "ownershipType" TEXT NOT NULL,
    "partnerType" TEXT NOT NULL,
    "website" TEXT,
    "vendorIndustryType" TEXT,
    "placeOfBusiness" TEXT NOT NULL,
    "bankName" TEXT,
    "accountNumber" TEXT,
    "ifscCode" TEXT,
    "bankDocument" TEXT,
    "gstType" TEXT,
    "gstNumber" TEXT,
    "gstCertificate" TEXT,
    "panNumber" TEXT,
    "panDocument" TEXT,
    "hasMsmeUdyog" TEXT,
    "msmeUdyogNumber" TEXT,
    "msmeUdyogCertificate" TEXT,
    "title" TEXT,
    "firstName" TEXT,
    "lastName" TEXT,
    "designation" TEXT,
    "countryCode" TEXT,
    "phoneNumber" TEXT,
    "hasEmail" TEXT,
    "email" TEXT,
    "addresses" JSONB,
    "turnoverExceedingTenCrore" TEXT,
    "hasFiledITR" TEXT,
    "acknowledgementNo2021" TEXT,
    "filingDate2021" TIMESTAMP(3),
    "acknowledgementNo2022" TEXT,
    "filingDate2022" TIMESTAMP(3),
    "acknowledgementNo2023" TEXT,
    "filingDate2023" TIMESTAMP(3),
    "submitterName" TEXT,
    "submitterDesignation" TEXT,
    "submitterEmail" TEXT,
    "declaration" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "FormSubmission_pkey" PRIMARY KEY ("id")
);
